# Generated by Django 5.0 on 2023-12-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='posted_by',
            field=models.CharField(default='admin', max_length=100),
            preserve_default=False,
        ),
    ]
